name: Compilar Mod Menu 32-bits

on:
  push:
    branches: [ main, master ] # Se activa cada vez que guardas cambios
  workflow_dispatch: # Permite activar la compilación manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el codigo del repositorio
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Configurar Android NDK
      uses: android-actions/setup-android@v3
      # Instala las herramientas necesarias automáticamente

    - name: Otorgar permisos al compilador Gradle
      run: chmod +x gradlew

    - name: Compilar APK (Solo 32 bits)
      run: ./gradlew assembleDebug

    - name: Subir el APK final a GitHub
      uses: actions/upload-artifact@v4
      with:
        name: ModMenu-RedmiA3
        path: app/build/outputs/apk/debug/app-debug.apk
